### ISSUE TITLE
Guide walkthrough: Getting Started pages

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#325]

**Comment by wbittles** [comment]
Step 1 install swift 

• You can then extract files to system root. ( not obvious how to achieve this)
• Where `${PATH}` is the path to your Swift installation.  ('${PATH}' points to existing env variable)
• For this installation method you need to have npm installed. (unbuntu offers the ability to install npm via system tools, which is broken. Should we recommend full node installation)

Step 2 next steps 
•      need to have git client installed 
•      kitura init fails ('Generator-Swiftserver-Projects' /home/wbittles/MyKituraApp: error: could not find source files for target(s): Generator-Swiftserver-Projects; use the 'path' property in the Swift 4 manifest to set a custom target path) Kitura init fails on Linux #42

**Comment by wbittles** [comment]
Next steps

Routing: Learn about routing and the two types Kitura supports. (the next step is actually logging)

**Comment by wbittles** [comment]
Kitura init creates a Package.swift file with the following 
 .testTarget(name: "ApplicationTests" , dependencies: [.target(name: "Application"), "Kitura","HeliumLogger" ])
This section is not referred to in any of the guides.

**Comment by Andrew-Lees11** [comment]
- Have updated the path instructions in pr #379.
- I think we can assume the user has git installed or will install it when they see the error message
- Kitura init has been fixed on linux
- CLI and macOS skip logging since it is added by default. SPM links to the logging section
- We need a testing guide. this should be raised as a separate issue.
