### ISSUE TITLE
Guide walkthrough: Logging pages

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#326]

**Comment by wbittles** [comment]
.Kitura Server Style Guide
Recommended Project structure does not match project structure generated by the CLI.
Below is the current generated structure
├── chart
│   └── mykituraapp
│       ├── bindings.yaml
│       ├── Chart.yaml
│       ├── templates
│       │   ├── basedeployment.yaml
│       │   ├── deployment.yaml
│       │   ├── hpa.yaml
│       │   ├── istio.yaml
│       │   └── service.yaml
│       └── values.yaml
├── cli-config.yml
├── debian
│   ├── changelog
│   ├── compat
│   ├── control
│   ├── install
│   └── rules
├── Dockerfile
├── Dockerfile-tools
├── iterative-dev.sh
├── Jenkinsfile
├── LICENSE
├── manifest.yml
├── Package.resolved
├── Package.swift
├── README.md
├── README.rtf
├── Sources
│   ├── Application
│   │   ├── Application.swift
│   │   ├── InitializationError.swift
│   │   ├── Metrics.swift
│   │   └── Routes
│   │       └── HealthRoutes.swift
│   └── MyKituraApp
│       └── main.swift
├── terraform
│   ├── main.tf
│   ├── output.tf
│   ├── scripts
│   │   ├── build.sh
│   │   ├── fetch-state.sh
│   │   ├── install.sh
│   │   ├── publish-state.sh
│   │   ├── start.sh
│   │   └── validate.sh
│   └── variables.tf
└── Tests
    ├── ApplicationTests
    │   └── RouteTests.swift
    └── LinuxMain.swift

**Comment by wbittles** [comment]
Kitura Server Style Guide
It's not obvious why the project needs to be rebuilt between step 2 and step 3

**Comment by wbittles** [comment]
Kitura Server Style Guide
Abruptly ends with no "next step" link after adding the book model

**Comment by wbittles** [comment]
HeliumLogger
Running the generated code after Step 2 to check output produces warning message and different output
wbittles@kitura-unbuntu-18:~/MyKituraApp$ swift run
[2019-05-09T12:26:27.310+01:00] [WARNING] [ConfigurationManager.swift:389 load(url:deserializerName:)] Unable to load data from URL /home/wbittles/MyKituraApp/config/mappings.json
[Thu May  9 12:26:27 2019] com.ibm.diagnostics.healthcenter.loader INFO: Swift Application Metrics
[2019-05-09T12:26:27.316+01:00] [INFO] [Metrics.swift:24 initializeMetrics(router:)] Initialized metrics.
[2019-05-09T12:26:27.318+01:00] [INFO] [HTTPServer.swift:229 listen(_:)] Listening on port 8080

**Comment by Andrew-Lees11** [comment]
These comments have been addressed in pr #379 
- The Style guide has been moved into create-a-server-spm. In this case the project structure is only what you create and doesn't include everything generated by the generator. We may want to describe the CLI generated project but are not covering that at the moment.
- The project did not need to be rebuilt and so that step has been removed
- Now the style guide is in SPM it has next steps to the routing section.
- Helium logger guide now says that the Logger.use is inside `Main.swift`
- The different messages and timestamps is due to logging from swift metrics which you do not get if you generate the project via spm.
