### ISSUE TITLE
Guide walkthrough: Database pages

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#334]

**Comment by wbittles** [comment]
Swift Kuery ORM
sudo apt-get install postgresql postgresql-contrib
probably need the client installed as well
need to create user before creating database like the following

wbittles@kitura-unbuntu-18:~/MyKituraApp$ sudo -u postgres psql
psql (10.8 (Ubuntu 10.8-0ubuntu0.18.04.1))
Type "help" for help.

postgres=#  CREATE USER wbittles;
CREATE ROLE
postgres=#  ALTER USER wbittles SUPERUSER CREATEDB;
ALTER ROLE

**Comment by wbittles** [comment]
Swift Kuery

- Open the `KueryRoutes.swift` file:
    touch Sources/Application/Routes/KueryRoutes.swift (should be 'open')

Step 2x: Install the PostgreSQL client (repeats from the ORM guide, the same 'wrong' instructions for linux.

**Comment by Andrew-Lees11** [comment]
A pr addressing these comments has been raised:
- A Line saying that on linux you need to create a user and a link to the database documentation for adding a user has been added
- extra % has been removed
- The Book and Booktable are different. I have modified the wording on our explination of the two to try and clear up why we have two models
- The Swift Kuery usage guide already has postgreSQL since you can't really use kuery without a plugin. Hopefully people are able to work out that you don't need to add it twice.
- I have added comments to the end example highlighting the sections that will be different if you used a different plugin.
