### ISSUE TITLE
Guide walkthrough: Sessions pages

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#350]

**Comment by wbittles** [comment]
The first iteration is now complete

**Comment by wbittles** [comment]
What are Sessions?
"Unlike the session cookies are stored client-side, " ?

**Comment by wbittles** [comment]
Next, create a new file, called SessionRawRoutes.swift, to contain the framework for our routes code:

this is usually accompanied by the correct directory such as Sources/Application/Routes/SessionRawRoutes.swift

**Comment by wbittles** [comment]
It would read better if we called out that we will use OpenAPI to test Codable sessions up front and made the necessary edits while building the sample.

**Comment by helenmasters** [comment]
@wbittles - please can you give me a line number for your comment "Unlike the session..." as I can't find this in the file?

**Comment by Andrew-Lees11** [comment]
a pr addressing these comments has now been raised:
- The "Unlike the session cookies are stored client-side" was fixed in an earlier pr
- Create folder instructions have been added
- The testing code from Raw sessions has been moved over to test using Curl. A comment linking to OpenAPI guide for testing was left in if somebody would like to use OpenAPI for testing.
